### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by akominch** [BaQs/pyEzviz#105]
I get an SSL error when I try to make a request. I originally encountered it in the HASS integration
Command:
```pyezviz -u <email> -p <pass> devices status```
Error: 
```HTTPSConnectionPool(host='apiieu.ezvizlife.com', port=443): Max retries exceeded with url: /v3/userdevices/v1/resources/pagelist?filter=CLOUD%2C+TIME_PLAN%2C+CONNECTION%2C+SWITCH%2CSTATUS%2C+WIFI%2C+NODISTURB%2C+KMS%2CP2P%2C+TIME_PLAN%2C+CHANNEL%2C+VTM%2CDETECTOR%2C+FEATURE%2C+CUSTOM_TAG%2C+UPGRADE%2CVIDEO_QUALITY%2C+QOS%2C+PRODUCTS_INFO%2C+FEATURE_INFO (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)')))```

I am also attaching a link to the issue in the home assistant repository – https://github.com/home-assistant/core/issues/91701

**Comment by RenierM26** [comment]
1) This might be caused by the region you are in? EZVIZ essentially has 3 regions. (EU, China and Russia)
2) If your account is on the EU servers, then it might be a time or OS issue (root certificates or something like that).

This doesn't seem like a common issue so leads me to think is one of the two above.
