### ISSUE TITLE
Any updates on pyezviz integration?

### ISSUE THREAD

**Issue by thisisbenwoo** [BaQs/pyEzviz#17]
Hello,

To begin with, thanks for creating this integration. I know that this integration was disabled in HA 0.115. I'm wondering if there has been any movement in re-enabling this? I'm simply hoping to get a binary sensor working for when the doorbell button is pressed. Many thanks.

ben

**Comment by RenierM26** [comment]
#19 

A workaround to this problem (until BaQs reviews and merges a pull request with the fix)
You can create a copy of the ezviz component from hassio, then edit the manifest.json file to use a pull request for pyezviz.

Example manifest.json making use of my fork as example. I've renamed the component so your "configuration.yaml" file will need to reference "ezviz_my" instead of "ezviz".

configuration.yaml:

stream:
camera:
 - platform: ezviz_my
*******al the rest according to hassio documentation on ezviz integration****

manifest.json changes on copy of official hassio ezviz component. The requirements section references my fork of pyEzviz but you could easily change this to BaQs with patch if you prefer that route. (Below will work)

{
  "domain": "ezviz_my",
  "name": "Ezviz_my",
  "documentation": "https://www.home-assistant.io/integrations/ezviz",
  "dependencies": [],
  "codeowners": ["@baqs"],
  "requirements": ["git+https://github.com/RenierM26/pyEzviz.git@master#pyezviz==0.1.5.6"]
}

**Comment by avol-io** [comment]
i tried the trick.. but where is the manifest to modify?
because i found that in homeassistant/lib/python3.8/site-packages/homeassistant/components/ezviz

**Comment by RenierM26** [comment]
Hi There, you'll need to copy the hassio ezviz component from their repository. (very similar to installing a custom_component).

the manifest file is in the ezviz component directory (Which should be a copy of the hassio component from their github repository).

**Comment by mindtripper** [comment]
Awesome. Thank you for taking the time to fix the component.

I have a question though.

Following the instructions. I am seeing the below issue when starting my Dockerized HA (latest build).

```
2020-12-20 12:36:31 ERROR (MainThread) [homeassistant.components.camera] Error while setting up ezviz_my platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_my/camera.py", line 91, in setup_platform
    camera["ezviz_camera"] = EzvizCamera(ezviz_client, camera_serial)
TypeError: __init__() missing 1 required positional argument: 'camerainfo'
```

This is the version of component:
```
bash-5.0# pip install pyezviz
Requirement already satisfied: pyezviz in /usr/local/lib/python3.8/site-packages (0.1.5.9)

```

Have I missed a step?

**Comment by BaQs** [comment]
Hi all, sorry for the delay!
We'll work on this with @RenierM26 and merge all that into the official HA module

Thx!

**Comment by thisisbenwoo** [comment]
> Hi all, sorry for the delay!
> We'll work on this with @RenierM26 and merge all that into the official HA module
> 
> Thx!

Thanks. Have held off because I don't want to add custom custom code..

**Comment by RenierM26** [comment]
Hi There,

We're working on updating the official HASS integration and making good progress. In the mean time you can use HACS custom repository: 

Custom repository : RenierM26/ha-ezviz
