### ISSUE TITLE
Changing status of alarm notification returns error

### ISSUE THREAD

**Issue by baxxter70** [BaQs/pyEzviz#41]
I have an issue when trying to enable or disable the alarm notification. I receive this error:
```
Impossible to decode response: Expecting value: line 1 column 1 (char 0)
Response was: <!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EDGE">
<meta charset="utf-8">
<meta HTTP-EQUIV="pragma" CONTENT="no-cache">
<meta HTTP-EQUIV="Cache-Control" CONTENT="no-cache, no-store">
...
```

It can be reproduced with this command:
`pyezviz -u XXXX -p XXXX camera --serial XXXX alarm --notify 1`

Note that this command works correctly:
`pyezviz -u XXXX -p XXXX --debug camera --serial XXXX alarm --sensibility 3`

Thanks

**Comment by RenierM26** [comment]
Hi @baxxter70,

This doesn't work at the moment due to recent changes. You can use the "change defense mode" in the interim.

![image](https://user-images.githubusercontent.com/66512715/113973915-5e73b380-983d-11eb-9c37-dedda0d803d3.png)

The api does some or other binary connection to this URL that I need to reverse engineer:

"casIp": "eucas.ezvizlife.com",
"casPort": 6500,

**Comment by baxxter70** [comment]
Hi @RenierM26,

Thanks for the workaround.

Good luck for the reverse engineering.

**Comment by RenierM26** [comment]
Hi @baxxter70 ,

Finally managed to reverse engineer the ezviz cas server connection/encryption types. With the latest version your should be able to enable/disable motion detection on individual cameras again.

**Comment by baxxter70** [comment]
Hi @RenierM26,

Thanks a lot, it works well.
